
Arena:
  PP_cavities:
    F20_20_B: true
    F20_20_G: true

    S40_40_B: true
    S40_40_G: true
    M20: true
    M30: true
  tables:
    1: 10
    2: 15
    3: 5
    4: 0
    6: PPT
    7: SH
    8: RTT
