
Tasks:
  BTT2:
    prep_time: 3
    exec_time: 6
    object_count: 6
    decoy_count: 3
    #table_height_2: 0

    table_height_0: 4
    table_height_5: 4
    table_height_10: 4
    table_height_15 : 4

    shelves_grasping: 2
    shelves_placing: 0
    pp: 0
    rt_grasping: 0
    rt_placing: 0
    arbitary_surface_count: 2
    obstacle_count: 2
    barrier_tape_count: 1

    ##Axis: true
    M20: true
    M30: true
    R20: true
    F20: false
    S40: false

    container_red: 2
    container_blue: 1
